### PR TITLE
improved index.html and Readme

### PR DESCRIPTION
**Pull request by ghost**
take a look [here](https://raghav9official.github.io/scrollSpy/)

### CODE REVIEW

**Comment by ghost** [comment]
this project needed a better page

**Comment by ut-01** [comment]
you have done a great job!

**Comment by ut-01** [comment]
How about I add you as a collaborator to this repository? @raghav9official

**Comment by ghost** [comment]
> How about I add you as a collaborator to this repository? @raghav9official

sure you can!

**Pull request merged**
